services:
    ros:
        build: ./ros/robot_ws
        restart: always
        privileged: true
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "4096M"
                reservations:
                    cpus: "0.2"
                    memory: "1024M"

    webfrontend:
        image: ghcr.io/foxglove/studio:latest
        ports:
            - "8080:8080"
        restart: always
